#Requires -Version 5.1
<#
.SYNOPSIS
    Create a new MCU project from this template, or apply the template to an
    existing STM32CubeMX project folder.

.DESCRIPTION
    Copies .vscode / cmake / scripts / App / .svd / .clangd / .clang-format /
    CMakeLists.txt / CMakePresets.json into the target directory, generates
    mcu.json from -Chip or the explicit parameters, then runs sync-mcu.ps1.

    If the target already contains mcu.json it is kept as-is unless -Force is used,
    so re-applying the template never destroys your chip settings.

    NOTE: this file is intentionally ASCII-only so that Windows PowerShell 5.1
    parses it correctly regardless of the system code page.

.PARAMETER Path
    Target project directory (created if missing).

.PARAMETER Chip
    Shortcut for a well-known chip; fills device / cpu / fpu / floatAbi /
    linkerScript / svd / openocdTarget / defines in one go.
    Built-in values: stm32f103c8 stm32f401re stm32f407vg stm32f411ce stm32f429zi
    stm32f446re stm32f746zg stm32h743zi stm32g071rb stm32g431rb stm32l431rc

.PARAMETER Force
    Overwrite an existing mcu.json.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts/new-project.ps1 ..\MyF407 -Chip stm32f407vg

.EXAMPLE
    # Apply the template to a project already generated by STM32CubeMX
    powershell -ExecutionPolicy Bypass -File scripts/new-project.ps1 ..\MyCubeProj -Chip stm32g431rb
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$Path,

    [string]$Chip,

    [string]$Device,
    [string]$Cpu,
    [string]$Fpu,
    [ValidateSet('hard', 'soft', 'softfp')]
    [string]$FloatAbi,
    [string]$LinkerScript,
    [string]$Svd,
    [string]$OpenocdTarget,

    # Enable float support in printf/scanf (CubeIDE's -u _printf_float -u _scanf_float).
    # Default on: leaving it off makes printf("%f") silently fail at runtime.
    # Set "floatIo": false in mcu.json to save roughly 14 KB of flash.
    [bool]$FloatIo = $true,

    [string[]]$Defines,

    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# -----------------------------------------------------------------------------
# Built-in chip table
# -----------------------------------------------------------------------------
$CHIPS = @{
    'stm32f103c8' = @{ device = 'STM32F103C8'; cpu = 'cortex-m3';     fpu = 'none';        abi = 'soft'; ld = 'STM32F103C8Tx_FLASH.ld';  svd = 'STM32F103.svd'; ocd = 'target/stm32f1x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32F103xB') }
    'stm32f401re' = @{ device = 'STM32F401RE'; cpu = 'cortex-m4';     fpu = 'fpv4-sp-d16'; abi = 'hard'; ld = 'STM32F401RETx_FLASH.ld'; svd = 'STM32F401.svd'; ocd = 'target/stm32f4x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32F401xE') }
    'stm32f407vg' = @{ device = 'STM32F407VG'; cpu = 'cortex-m4';     fpu = 'fpv4-sp-d16'; abi = 'hard'; ld = 'STM32F407VGTx_FLASH.ld'; svd = 'STM32F407.svd'; ocd = 'target/stm32f4x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32F407xx') }
    'stm32f411ce' = @{ device = 'STM32F411CE'; cpu = 'cortex-m4';     fpu = 'fpv4-sp-d16'; abi = 'hard'; ld = 'STM32F411CEUx_FLASH.ld'; svd = 'STM32F411.svd'; ocd = 'target/stm32f4x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32F411xE') }
    'stm32f429zi' = @{ device = 'STM32F429ZI'; cpu = 'cortex-m4';     fpu = 'fpv4-sp-d16'; abi = 'hard'; ld = 'STM32F429ZITx_FLASH.ld'; svd = 'STM32F429.svd'; ocd = 'target/stm32f4x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32F429xx') }
    'stm32f446re' = @{ device = 'STM32F446RE'; cpu = 'cortex-m4';     fpu = 'fpv4-sp-d16'; abi = 'hard'; ld = 'STM32F446RETx_FLASH.ld'; svd = 'STM32F446.svd'; ocd = 'target/stm32f4x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32F446xx') }
    'stm32f746zg' = @{ device = 'STM32F746ZG'; cpu = 'cortex-m7';     fpu = 'fpv5-sp-d16'; abi = 'hard'; ld = 'STM32F746ZGTx_FLASH.ld'; svd = 'STM32F746.svd'; ocd = 'target/stm32f7x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32F746xx') }
    'stm32h743zi' = @{ device = 'STM32H743ZI'; cpu = 'cortex-m7';     fpu = 'fpv5-d16';    abi = 'hard'; ld = 'STM32H743ZITx_FLASH.ld'; svd = 'STM32H743.svd'; ocd = 'target/stm32h7x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32H743xx', 'CORE_CM7') }
    'stm32g071rb' = @{ device = 'STM32G071RB'; cpu = 'cortex-m0plus'; fpu = 'none';        abi = 'soft'; ld = 'STM32G071RBTx_FLASH.ld'; svd = 'STM32G071.svd'; ocd = 'target/stm32g0x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32G071xx') }
    'stm32g431rb' = @{ device = 'STM32G431RB'; cpu = 'cortex-m4';     fpu = 'fpv4-sp-d16'; abi = 'hard'; ld = 'STM32G431RBTx_FLASH.ld'; svd = 'STM32G431.svd'; ocd = 'target/stm32g4x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32G431xx') }
    'stm32l431rc' = @{ device = 'STM32L431RC'; cpu = 'cortex-m4';     fpu = 'fpv4-sp-d16'; abi = 'hard'; ld = 'STM32L431RCTx_FLASH.ld'; svd = 'STM32L431.svd'; ocd = 'target/stm32l4x.cfg'; defs = @('USE_HAL_DRIVER', 'STM32L431xx') }
}

# -----------------------------------------------------------------------------
# 1. Resolve paths
# -----------------------------------------------------------------------------
$templateRoot = Split-Path -Parent $PSScriptRoot
if (-not $templateRoot) { $templateRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path }
$targetRoot = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)

# -----------------------------------------------------------------------------
# 2. Build the effective configuration: chip table first, explicit params win
# -----------------------------------------------------------------------------
$cfg = @{
    device        = 'STM32F407VG'
    cpu           = 'cortex-m4'
    fpu           = 'fpv4-sp-d16'
    floatAbi      = 'hard'
    linkerScript  = 'STM32F407VGTx_FLASH.ld'
    svd           = 'STM32F407.svd'
    openocdTarget = 'target/stm32f4x.cfg'
    defines       = @('USE_HAL_DRIVER', 'STM32F407xx')
}

if ($Chip) {
    $key = $Chip.ToLowerInvariant()
    if (-not $CHIPS.ContainsKey($key)) {
        $available = ($CHIPS.Keys | Sort-Object) -join ' '
        throw "Unknown chip '$Chip'. Built-in: $available`nOr skip -Chip and pass -Device / -Cpu / -Fpu / -LinkerScript / -Svd / -OpenocdTarget / -Defines instead."
    }
    $preset = $CHIPS[$key]
    $cfg.device        = $preset.device
    $cfg.cpu           = $preset.cpu
    $cfg.fpu           = $preset.fpu
    $cfg.floatAbi      = $preset.abi
    $cfg.linkerScript  = $preset.ld
    $cfg.svd           = $preset.svd
    $cfg.openocdTarget = $preset.ocd
    $cfg.defines       = $preset.defs
}

if ($PSBoundParameters.ContainsKey('Device'))        { $cfg.device        = $Device }
if ($PSBoundParameters.ContainsKey('Cpu'))           { $cfg.cpu           = $Cpu }
if ($PSBoundParameters.ContainsKey('Fpu'))           { $cfg.fpu           = $Fpu }
if ($PSBoundParameters.ContainsKey('FloatAbi'))      { $cfg.floatAbi      = $FloatAbi }
if ($PSBoundParameters.ContainsKey('LinkerScript'))  { $cfg.linkerScript  = $LinkerScript }
if ($PSBoundParameters.ContainsKey('Svd'))           { $cfg.svd           = $Svd }
if ($PSBoundParameters.ContainsKey('OpenocdTarget')) { $cfg.openocdTarget = $OpenocdTarget }
if ($PSBoundParameters.ContainsKey('Defines'))       { $cfg.defines       = $Defines }

# -----------------------------------------------------------------------------
# 3. Prepare target directory
# -----------------------------------------------------------------------------
if (Test-Path -LiteralPath $targetRoot) {
    $existing = @(Get-ChildItem -Force -LiteralPath $targetRoot)
    if ($existing.Count -gt 0) {
        Write-Host "[new-project] target exists, refreshing template files: $targetRoot" -ForegroundColor Yellow
    }
} else {
    New-Item -ItemType Directory -Path $targetRoot -Force | Out-Null
    Write-Host "[new-project] created directory: $targetRoot"
}

# -----------------------------------------------------------------------------
# 4. Copy template files
# -----------------------------------------------------------------------------
$entries = @(
    '.vscode', 'cmake', 'scripts', 'App', '.svd', '.github',
    '.clangd', '.clang-format', '.format-exclude', '.gitignore',
    'CMakeLists.txt', 'CMakePresets.json'
)

foreach ($entry in $entries) {
    $src = Join-Path $templateRoot $entry
    if (Test-Path -LiteralPath $src) {
        Copy-Item -LiteralPath $src -Destination $targetRoot -Recurse -Force
        Write-Host "  + $entry"
    }
}

# -----------------------------------------------------------------------------
# 5. Generate mcu.json (never clobber an existing one unless -Force)
# -----------------------------------------------------------------------------
$mcuPath = Join-Path $targetRoot 'mcu.json'
if ((Test-Path -LiteralPath $mcuPath) -and (-not $Force)) {
    Write-Host "[new-project] mcu.json already exists - left untouched (use -Force to overwrite)" -ForegroundColor Yellow
} else {
    # Hand-formatted so the file stays readable (ConvertTo-Json in PS 5.1 pads oddly)
    $definesJson = (($cfg.defines | ForEach-Object { '    "' + $_ + '"' }) -join ",`n")
    $floatIoJson = if ($FloatIo) { 'true' } else { 'false' }
    $mcuJson = @"
{
  "name": "$($cfg.device)",
  "device": "$($cfg.device)",
  "cpu": "$($cfg.cpu)",
  "fpu": "$($cfg.fpu)",
  "floatAbi": "$($cfg.floatAbi)",
  "linkerScript": "$($cfg.linkerScript)",
  "svd": "$($cfg.svd)",
  "openocdTarget": "$($cfg.openocdTarget)",
  "floatIo": $floatIoJson,
  "defines": [
$definesJson
  ]
}
"@
    [System.IO.File]::WriteAllText($mcuPath, $mcuJson, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "  + mcu.json ($($cfg.device))"
}

# -----------------------------------------------------------------------------
# 6. Sync launch.json
# -----------------------------------------------------------------------------
& (Join-Path $targetRoot 'scripts/sync-mcu.ps1') -ProjectRoot $targetRoot

Write-Host ""
Write-Host "[new-project] done: $targetRoot" -ForegroundColor Green
Write-Host "Next steps:"
Write-Host "  1. Generate code with STM32CubeMX in that folder (pick 'Makefile' toolchain to avoid"
Write-Host "     fighting over CMakeLists.txt; CMake toolchain also works, just re-apply the template)"
Write-Host "  2. Put the generated .ld file in the project root (or edit linkerScript in mcu.json)"
Write-Host "  3. Drop the SVD file into .svd/ (optional, enables the peripheral register view)"
Write-Host "  4. Open the folder in VSCode and press Ctrl+Shift+B to build"
